#!/bin/sh
# virn, Copyright (C) 2007-2010 by Jonas Kramer. All rights reserved.
# Published under the terms of the GNU General Public License (GPL).

# This is a more portable BASH remake of my old script "vimove" which depended
# on ZSH.

die() {
	echo "$@" >&2
	exit 1
}

# Verify that there's an $EDITOR defined.
[ -z "$EDITOR" ] && die '$EDITOR not defined.'

# Exit before doing anything if there are no arguments anyway.
[ $# -eq 0 ] && die 'Missing file operand.'

# Create targets file.
targets="/tmp/virn-$$"
trap "rm -f $targets" EXIT
for file; do echo "$file"; done >> $targets

# Start the $EDITOR so we can edit our file names.
if $EDITOR $targets; then
	count=`wc -l <$targets`

	# Exit with error message if number of arguments and line count of
	# targets file differ.
	[ "$count" -ne $# ] && die 'Numbers of files mismatch.'

	# Read targets file line by line and rename the source
	# files from ARGV appropriately.
	while read target; do
		source=$1
		[ "$source" != "$target" ] && mv -f -- "$source" "$target"
		shift
	done < $targets
fi
